#!/usr/bin/env bash
set -euo pipefail

# Docker DNS e2e cases for `debug dns`.
#
# All cases use the same observable contract:
# 1. Arrange the container to look like one DNS-management setup.
# 2. Put the original upstream DNS server at a deterministic local address, or
#    omit original upstream configuration for *-no-upstream cases and pass that
#    address as a DNSProvider constructor fallback through the debug binary.
# 3. Start `debug dns`; it must detect the expected DnsMode and instantiate the
#    matching DNSProvider.
# 4. Run a normal system resolver query with dig. The query must go through the
#    DNS server installed by debug dns and appear in the debug log.
# 5. The query must still receive the upstream's deterministic answer, proving
#    the provider forwarded to the original upstream instead of looping back to
#    itself.
#
# Expected behavior per case:
# - direct: no recognized owner in /etc/resolv.conf, so DnsMode is "direct".
#   Direct writes /etc/resolv.conf with nameserver 127.0.0.1.
# - debian-resolvconf: /etc/resolv.conf is marked as resolvconf-owned and the
#   installed resolvconf implementation is Debian resolvconf, so DnsMode is
#   "debian-resolvconf". The sysnet-linux resolvconf record points at 127.0.0.1.
# - openresolv: /etc/resolv.conf is marked as resolvconf-owned and the installed
#   resolvconf implementation is openresolv, so DnsMode is "openresolv". The
#   sysnet-linux openresolv record points at 127.0.0.1.
# - systemd-resolved: a system bus and systemd-resolved are running,
#   /etc/resolv.conf points at the resolved stub 127.0.0.53, and resolved has
#   the mock upstream configured on eth0, so DnsMode is "systemd-resolved".
#   Resolved routes system queries to the debug TUN DNS.
# - systemd-resolved-split: resolved has two route-only domains on two links,
#   each with a different upstream. Queries must return the answer for the
#   matching route.
#
# Docker bind-mounts /etc/resolv.conf into containers. The resolvconf packages
# normally maintain /etc/resolv.conf through a symlink to generated state, but
# they cannot replace Docker's mount. For resolvconf cases we still assert the
# real provider-owned resolvconf record, then copy the expected generated
# nameserver into Docker's mounted file before running dig.

case_name="${1:?usage: sysnet-dns-e2e <direct|direct-no-upstream|debian-resolvconf|debian-resolvconf-no-upstream|openresolv|openresolv-no-upstream|systemd-resolved|systemd-resolved-no-upstream|systemd-resolved-split>}"
expected_mode="${case_name%-no-upstream}"
if [[ "$case_name" == systemd-resolved-* ]]; then
	expected_mode="systemd-resolved"
fi
no_upstream=0
if [[ "$case_name" == *-no-upstream ]]; then
	no_upstream=1
fi
query_name="sysnet-${case_name//[^a-zA-Z0-9]/-}-$$.e2e.test"
debug_log="/tmp/sysnet-debug.log"
upstream_log="/tmp/sysnet-upstream.log"
upstream_addr="127.0.0.54"

fail() {
	echo "FAIL[$case_name]: $*" >&2
	echo "--- debug log ---" >&2
	if [[ -f "$debug_log" ]]; then cat "$debug_log" >&2; fi
	echo "--- upstream log ---" >&2
	for log in /tmp/sysnet-upstream*.log; do
		if [[ -f "$log" ]]; then
			echo "### $log" >&2
			cat "$log" >&2
		fi
	done
	echo "--- /etc/resolv.conf ---" >&2
	cat /etc/resolv.conf >&2 || true
	exit 1
}

wait_for_log() {
	local pattern="$1"
	local file="$2"
	local deadline=$((SECONDS + 20))
	while (( SECONDS < deadline )); do
		if [[ -f "$file" ]] && grep -Eq "$pattern" "$file"; then
			return 0
		fi
		sleep 0.2
	done
	return 1
}

cleanup_pids=()
cleanup() {
	local status=$?
	for pid in "${cleanup_pids[@]:-}"; do
		if kill -0 "$pid" 2>/dev/null; then
			kill "$pid" 2>/dev/null || true
			wait "$pid" 2>/dev/null || true
		fi
	done
	exit "$status"
}
trap cleanup EXIT

start_upstream() {
	local addr="${1:-$upstream_addr}"
	local answer="${2:-203.0.113.10}"
	local log="${3:-$upstream_log}"
	SYSNET_DNS_E2E_UPSTREAM_ADDR="$addr" \
		SYSNET_DNS_E2E_UPSTREAM_ANSWER="$answer" \
		python3 /usr/local/lib/sysnet-dns-e2e/upstream_dns.py >"$log" 2>&1 &
	cleanup_pids+=("$!")
	wait_for_log "upstream DNS listening" "$log" || fail "upstream DNS did not start on $addr"
}

write_direct_resolvconf() {
	cat > /etc/resolv.conf <<'EOF'
# static resolver for sysnet-linux docker e2e
nameserver 127.0.0.54
EOF
}

write_direct_resolvconf_without_upstreams() {
	cat > /etc/resolv.conf <<'EOF'
# static resolver for sysnet-linux docker e2e
# no original nameservers
EOF
}

write_resolvconf_owned_file() {
	cat > /etc/resolv.conf <<'EOF'
# resolv.conf(5) file generated by resolvconf
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.54
EOF
}

write_resolvconf_owned_file_without_upstreams() {
	cat > /etc/resolv.conf <<'EOF'
# resolv.conf(5) file generated by resolvconf
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# no original nameservers
EOF
}

start_systemd_resolved() {
	local configure_upstream="${1:-1}"
	mkdir -p /run/dbus /etc/systemd
	local upstream_octets
	local upstream_ifidx
	dbus-daemon --system --fork
	cat > /etc/systemd/resolved.conf <<'EOF'
[Resolve]
DNSStubListener=yes
FallbackDNS=
EOF
	/lib/systemd/systemd-resolved &
	cleanup_pids+=("$!")
	local deadline=$((SECONDS + 20))
	while (( SECONDS < deadline )); do
		if busctl --system call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.DBus.Peer Ping >/dev/null 2>&1; then
			break
		fi
		sleep 0.2
	done
	busctl --system call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.DBus.Peer Ping >/dev/null 2>&1 || fail "systemd-resolved did not register on D-Bus"
	if [[ "$configure_upstream" == 1 ]]; then
		upstream_ifidx="$(cat /sys/class/net/eth0/ifindex)"
		upstream_octets="${upstream_addr//./ }"
		busctl --system call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager SetLinkDNS "ia(iay)" "$upstream_ifidx" 1 2 4 $upstream_octets || fail "failed to configure resolved upstream DNS"
		busctl --system call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager SetLinkDefaultRoute "ib" "$upstream_ifidx" true || fail "failed to configure resolved default route"
		busctl --system call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager SetLinkDomains "ia(sb)" "$upstream_ifidx" 1 "." true || fail "failed to configure resolved route-only root domain"
	fi
	cat > /etc/resolv.conf <<'EOF'
# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
nameserver 127.0.0.53
EOF
}

configure_resolved_link_dns() {
	local ifname="$1"
	local addr="$2"
	local domain="$3"
	local default_route="${4:-false}"
	local ifidx
	local octets
	ifidx="$(cat "/sys/class/net/$ifname/ifindex")"
	octets="${addr//./ }"
	busctl --system call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager SetLinkDNS "ia(iay)" "$ifidx" 1 2 4 $octets || fail "failed to configure resolved DNS for $ifname"
	busctl --system call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager SetLinkDefaultRoute "ib" "$ifidx" "$default_route" || fail "failed to configure resolved default route for $ifname"
	busctl --system call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager SetLinkDomains "ia(sb)" "$ifidx" 1 "$domain" true || fail "failed to configure resolved domain $domain for $ifname"
}

run_debug() {
	local fallback_env=()
	if [[ "$no_upstream" == 1 ]]; then
		fallback_env=("SYSNET_DEBUG_DNS_FALLBACKS=${upstream_addr}:53")
	fi
	env "${fallback_env[@]}" /usr/local/bin/sysnet-debug dns >"$debug_log" 2>&1 &
	cleanup_pids+=("$!")
	wait_for_log "^${expected_mode} <nil>$" "$debug_log" || fail "debug dns did not report DnsMode $expected_mode"
	wait_for_log "proxying DNS on .*:53 until Ctrl\\+C" "$debug_log" || fail "debug dns did not start proxying"
}

assert_query() {
	local name="${1:-$query_name}"
	local answer="${2:-203.0.113.10}"
	local server="${3:-}"
	local out
	local dig_args=(+time=2 +tries=1 +short)
	if [[ -n "$server" ]]; then
		dig_args+=("@$server")
	fi
	if ! out="$(dig "${dig_args[@]}" "$name" A 2>&1)"; then
		fail "dig failed: $out"
	fi
	if ! grep -q "$answer" <<<"$out"; then
		fail "dig returned unexpected answer: $out"
	fi
	wait_for_log "dns request .*${name}\\./1/1" "$debug_log" || fail "debug dns did not log intercepted query $name"
}

debug_dns_addr() {
	sed -n 's/^proxying DNS on \([^:]*\):53 until Ctrl+C$/\1/p' "$debug_log" | tail -n1
}

assert_upstream_query() {
	local log="$1"
	local name="$2"
	wait_for_log "upstream DNS query .*name=${name}\\." "$log" || fail "upstream did not receive $name"
}

mirror_resolvconf_record_to_docker_resolvconf() {
	local record="$1"
	local record_contents
	record_contents="$(resolvconf -l "$record" 2>/dev/null || resolvconf -l 2>/dev/null)"
	if ! grep -q '^nameserver 127\.0\.0\.1$' <<<"$record_contents"; then
		fail "resolvconf record $record does not point at 127.0.0.1"
	fi
	cat > /etc/resolv.conf <<'EOF'
# resolv.conf(5) file generated by resolvconf for sysnet-linux Docker e2e
# Docker keeps this path mounted, so the test mirrors the generated record.
nameserver 127.0.0.1
EOF
}

case "$case_name" in
	direct|direct-no-upstream)
		start_upstream
		if [[ "$no_upstream" == 1 ]]; then
			write_direct_resolvconf_without_upstreams
		else
			write_direct_resolvconf
		fi
		run_debug
		grep -q '^nameserver 127\.0\.0\.1$' /etc/resolv.conf || fail "Direct did not install 127.0.0.1 in /etc/resolv.conf"
		assert_query
		;;
	debian-resolvconf|debian-resolvconf-no-upstream)
		start_upstream
		if [[ "$no_upstream" == 1 ]]; then
			write_resolvconf_owned_file_without_upstreams
		else
			write_resolvconf_owned_file
		fi
		resolvconf --version >/tmp/resolvconf-version.log 2>&1 || true
		grep -q '^Debian resolvconf' /tmp/resolvconf-version.log || fail "resolvconf --version did not identify Debian resolvconf"
		run_debug
		mirror_resolvconf_record_to_docker_resolvconf sysnet-linux
		assert_query
		;;
	openresolv|openresolv-no-upstream)
		start_upstream
		if [[ "$no_upstream" == 1 ]]; then
			write_resolvconf_owned_file_without_upstreams
		else
			write_resolvconf_owned_file
		fi
		resolvconf --version >/tmp/resolvconf-version.log 2>&1 || fail "expected openresolv --version to succeed"
		run_debug
		mirror_resolvconf_record_to_docker_resolvconf sysnet-linux
		assert_query
		;;
	systemd-resolved|systemd-resolved-no-upstream)
		upstream_addr="$(ip -4 -o addr show dev eth0 | awk '{split($4, a, "/"); print a[1]; exit}')"
		start_upstream
		if [[ "$no_upstream" == 1 ]]; then
			start_systemd_resolved 0
		else
			start_systemd_resolved 1
		fi
		run_debug
		assert_query
		;;
	systemd-resolved-split)
		corp_addr="10.53.1.1"
		public_addr="10.53.2.1"
		ip link add sysnetdns1 type dummy
		ip link add sysnetdns2 type dummy
		ip addr add "$corp_addr/32" dev sysnetdns1
		ip addr add "$public_addr/32" dev sysnetdns2
		ip link set sysnetdns1 up
		ip link set sysnetdns2 up
		start_upstream "$corp_addr" "203.0.113.11" "/tmp/sysnet-upstream-corp.log"
		start_upstream "$public_addr" "203.0.113.12" "/tmp/sysnet-upstream-public.log"
		start_systemd_resolved 0
		configure_resolved_link_dns sysnetdns1 "$corp_addr" "corp.test" false
		configure_resolved_link_dns sysnetdns2 "$public_addr" "public.test" false
		run_debug
		debug_addr="$(debug_dns_addr)"
		[[ -n "$debug_addr" ]] || fail "could not find debug DNS address"
		corp_query="sysnet-split-corp-$$.corp.test"
		public_query="sysnet-split-public-$$.public.test"
		assert_query "$corp_query" "203.0.113.11" "$debug_addr"
		assert_query "$public_query" "203.0.113.12" "$debug_addr"
		assert_upstream_query "/tmp/sysnet-upstream-corp.log" "$corp_query"
		assert_upstream_query "/tmp/sysnet-upstream-public.log" "$public_query"
		;;
	*)
		fail "unknown case $case_name"
		;;
esac

echo "PASS[$case_name]: mode=$expected_mode query=$query_name"
